apiVersion: apps/v1
kind: Deployment
metadata:
  name: purimmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purimmonitor
  template:
    metadata:
      labels:
        app: purimmonitor
    spec:
      containers:
        - name: purimmonitor
          image: purimmonitor:latest
          ports:
            - containerPort: 5000
